
# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  NUGET_TOKEN: ${{ secrets.NUGET_PWD }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      id: build-nuget 
      run: dotnet build --no-restore -c Release
    - name: Pack
      run: dotnet pack --no-build --configuration Release
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Get version
      id: package_version
      uses: kzrnm/get-net-sdk-project-versions-action@v2
      with:
          proj-path: Gis.Net/Gis.Net.csproj
    - name: Push Nuget Packages
      uses: EasyDesk/action-nuget-push@v1.0.0
      with:
        nuget-api-key: ${{ secrets.NUGET_PWD }}
        nuget-url: https://nuget.pkg.github.com/EMP-Projects/index.json
        publish-dir: .
