
# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore -c Release
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Get version
      id: package_version
      uses: kzrnm/get-net-sdk-project-versions-action@v2
      with:
          proj-path: Gis.Net/Gis.Net.csproj
    - name: Publish
      run: dotnet nuget add source --username gzileni --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/EMP-Projects/index.json"
    - name: Push
      run: dotnet nuget push "Gis.net/bin/Release/Gis.Net.${{ steps.package_version.outputs.package-version }}.nupkg"  --api-key ${{ secrets.GITHUB_TOKEN }} --source "github"
